version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.adarshr.test-logger
    versions:
    - 2.1.1
