version: '3'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EKO_Vortraege
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - volume:/var/lib/mysql
    networks:
      - network

  spring:
    image: openjdk:10-jre-slim
    container_name: spring
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EKO_Vortraege
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./build/libs/enkovortraege-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - network

volumes:
  volume:
networks:
  network:
